local _M = {}

_M.SERVICE_PROTOCOLS_HTTP = "http"
_M.SERVICE_PROTOCOLS_HTTPS = "https"

_M.UPSTREAM_NODE_DEFAULT_PORT = 80
_M.UPSTREAM_NODE_DEFAULT_WEIGHT = 1
_M.UPSTREAM_NODE_DEFAULT_TIMEOUT = 1
_M.UPSTREAM_NODE_DEFAULT_INTERVAL = 5
_M.UPSTREAM_NODE_DEFAULT_ENABLED_TRUE = true
_M.UPSTREAM_NODE_DEFAULT_ENABLED_FALSE = false
_M.UPSTREAM_NODE_DEFAULT_HEALTH = "HEALTH"
_M.UPSTREAM_NODE_DEFAULT_UNHEALTH = "UNHEALTH"

return _M

