CREATE TABLE IF NOT EXISTS `apiok_access_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `timestamp` INT UNSIGNED NOT NULL COMMENT '请求时间戳',
  `request_method` VARCHAR(10) NOT NULL COMMENT '请求方法',
  `request_uri` VARCHAR(2048) NOT NULL COMMENT '请求URI',
  `request_path` VARCHAR(2048) NOT NULL COMMENT '请求路径',
  `request_query_string` TEXT COMMENT '查询字符串',
  `request_protocol` VARCHAR(20) COMMENT '协议版本',
  `remote_addr` VARCHAR(45) NOT NULL COMMENT '客户端IP',
  `remote_port` INT UNSIGNED COMMENT '客户端端口',
  `server_addr` VARCHAR(45) COMMENT '服务器IP',
  `server_port` INT UNSIGNED COMMENT '服务器端口',
  `request_host` VARCHAR(255) COMMENT '请求Host',
  `request_headers` TEXT COMMENT '请求头(JSON)',
  `request_args` TEXT COMMENT '请求参数(JSON)',
  `request_body` LONGTEXT COMMENT '请求体',
  `response_status` INT UNSIGNED NOT NULL COMMENT '响应状态码',
  `response_headers` TEXT COMMENT '响应头(JSON)',
  `response_body` LONGTEXT COMMENT '响应体',
  `upstream_response_time` VARCHAR(50) COMMENT '上游响应时间',
  `upstream_connect_time` VARCHAR(50) COMMENT '上游连接时间',
  `request_time` DECIMAL(10,3) NOT NULL COMMENT '请求处理时间(秒)',
  `bytes_sent` BIGINT UNSIGNED NOT NULL COMMENT '发送字节数',
  `service_name` VARCHAR(255) COMMENT '服务名称',
  `router_name` VARCHAR(255) COMMENT '路由名称',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `idx_timestamp` (`timestamp`),
  INDEX `idx_remote_addr` (`remote_addr`),
  INDEX `idx_response_status` (`response_status`),
  INDEX `idx_service_name` (`service_name`),
  INDEX `idx_router_name` (`router_name`),
  INDEX `idx_request_method` (`request_method`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='访问日志表';

